### ISSUE TITLE
No such module 'PromisedFuture'

### ISSUE THREAD

**Issue by dmarras** [AladinWay/PromisedFuture#1]
Hi,
i integrated it library with cocoapods and all goes well.
I'm able to see the PromisedFuture folded in installed Pods and also .h file
But when try to import PromisedFuture in swift code get this error No such module 'PromisedFuture'
I'm using xcode 9

Thanks

**Comment by AladinWay** [comment]
@dmarras Thank you for using `PromisedFuture` I have fixed the issue in version `1.0.1`
