### ISSUE TITLE
After new release, Swift asks to include a second parameter when returning Futures

### ISSUE THREAD

**Issue by angelsalinasreecast** [AladinWay/PromisedFuture#4]
Hi!,

After updating the pod for PromisedFuture and reviewing the latest closed issues, I've seen you updated the library to use the new Swift Result.

However, in my case, XCode is asking (in a lot of instances) to include a second argument when specifying that a function returns a function. Which wasn't the case up until now (example screenshot attached).

![image](https://user-images.githubusercontent.com/65187495/81595098-34620900-93c2-11ea-9905-7fd694834303.png)

Just wondering if this is an expected behavior since the last update. In any other case, could you please provide some guidance on how to fix it?

Thanks for your help!

**Comment by AladinWay** [comment]
Since now we use the Swift 5  `Result` type which enforces typed errors you need to provide the type of `Error`. Updating your code to `-> Future<Any, Error>` should works fine. But you can still use the previous version if you prefer not to use the  enforced Typed errors.

**Comment by angelsalinasreecast** [comment]
OK. Thanks for your prompt answer. I'll close the issue then.
Btw, great great work with this library. Really appreciate it.
